/**
 * SEPP Telescopic FQDN Mapping API
 * SEPP Telescopic FQDN Mapping Service.   © 2026, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.3.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
#include "ApiBase.h"

namespace oai::sepp::api {

ApiBase::ApiBase(const std::shared_ptr<Pistache::Rest::Router> &rtr)
    : router(rtr) {}

} // namespace oai::sepp::api