/**
 * N32 Handshake API
 * N32-c Handshake Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.4.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "N32FErrorReportApi.h"
#include "Helpers.h"
#include "sbi_helper.hpp"
#include "sepp_config.hpp"

namespace oai::sepp::api {

using namespace oai::_3gpp::model::helpers;
using namespace oai::_3gpp::model;
using namespace oai::common::sbi;

const std::string N32FErrorReportApi::base = "/n32c-handshake/v1";

N32FErrorReportApi::N32FErrorReportApi(
    const std::shared_ptr<Pistache::Rest::Router> &rtr)
    : ApiBase(rtr) {}

void N32FErrorReportApi::init() { setupRoutes(); }

void N32FErrorReportApi::setupRoutes() {
  using namespace Pistache::Rest;

  Routes::Post(
      *router, base + "/n32f-error",
      Routes::bind(&N32FErrorReportApi::post_n32f_error_handler, this));

  // Default handler, called when a route is not found
  router->addCustomHandler(Routes::bind(
      &N32FErrorReportApi::n32_f_error_report_api_default_handler, this));
}

void N32FErrorReportApi::handleParsingException(
    const std::exception &ex,
    Pistache::Http::ResponseWriter &response) const noexcept {
  std::pair<Pistache::Http::Code, std::string> codeAndError =
      handleParsingException(ex);
  response.send(codeAndError.first, codeAndError.second);
}

std::pair<Pistache::Http::Code, std::string>
N32FErrorReportApi::handleParsingException(
    const std::exception &ex) const noexcept {
  try {
    throw;
  } catch (nlohmann::detail::exception &e) {
    return std::make_pair(Pistache::Http::Code::Bad_Request, e.what());
    //    } catch (org::openapitools::server::helpers::ValidationException &e) {
    //       return std::make_pair(Pistache::Http::Code::Bad_Request, e.what());
  } catch (std::exception &e) {
    return std::make_pair(Pistache::Http::Code::Internal_Server_Error,
                          e.what());
  }
}

void N32FErrorReportApi::handleOperationException(
    const std::exception &ex,
    Pistache::Http::ResponseWriter &response) const noexcept {
  std::pair<Pistache::Http::Code, std::string> codeAndError =
      handleOperationException(ex);
  response.send(codeAndError.first, codeAndError.second);
}

std::pair<Pistache::Http::Code, std::string>
N32FErrorReportApi::handleOperationException(
    const std::exception &ex) const noexcept {
  return std::make_pair(Pistache::Http::Code::Internal_Server_Error, ex.what());
}

void N32FErrorReportApi::post_n32f_error_handler(
    const Pistache::Rest::Request &request,
    Pistache::Http::ResponseWriter response) {
  try {

    // Getting the body param

    N32fErrorInfo n32fErrorInfo;

    try {
      nlohmann::json::parse(request.body()).get_to(n32fErrorInfo);
      n32fErrorInfo.validate();
    } catch (std::exception &e) {
      this->handleParsingException(e, response);
      return;
    }

    try {

      this->post_n32f_error(n32fErrorInfo, response);
    } catch (Pistache::Http::HttpError &e) {
      response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
      return;
    } catch (std::exception &e) {
      this->handleOperationException(e, response);
      return;
    }

  } catch (std::exception &e) {
    response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}

void N32FErrorReportApi::n32_f_error_report_api_default_handler(
    const Pistache::Rest::Request &, Pistache::Http::ResponseWriter response) {
  response.send(Pistache::Http::Code::Not_Found,
                "The requested method does not exist");
}

} // namespace oai::sepp::api
