/**
 * N32 Handshake API
 * N32-c Handshake Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.4.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * N32FContextTerminateApi.h
 *
 *
 */

#ifndef N32FContextTerminateApi_H_
#define N32FContextTerminateApi_H_

#include "ApiBase.h"

#include <pistache/http.h>
#include <pistache/http_headers.h>
#include <pistache/router.h>

#include <optional>
#include <utility>

#include "N32fContextInfo.h"
#include "ProblemDetails.h"

namespace oai::sepp::api {

class N32FContextTerminateApi : public ApiBase {
public:
  explicit N32FContextTerminateApi(
      const std::shared_ptr<Pistache::Rest::Router> &rtr);
  ~N32FContextTerminateApi() override = default;
  void init() override;

  static const std::string base;

private:
  void setupRoutes();

  void post_n32f_terminate_handler(const Pistache::Rest::Request &request,
                                   Pistache::Http::ResponseWriter response);
  void n32_f_context_terminate_api_default_handler(
      const Pistache::Rest::Request &request,
      Pistache::Http::ResponseWriter response);

  /// <summary>
  /// Helper function to handle unexpected Exceptions during Parameter parsing
  /// and validation. May be overridden to return custom error formats. This is
  /// called inside a catch block. Important: When overriding, do not call
  /// `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual void handleParsingException(
      const std::exception &ex,
      Pistache::Http::ResponseWriter &response) const noexcept;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during Parameter parsing
  /// and validation. May be overridden to return custom error formats. This is
  /// called inside a catch block. Important: When overriding, do not call
  /// `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string>
  handleParsingException(const std::exception &ex) const noexcept;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during processing of the
  /// request in handler functions. May be overridden to return custom error
  /// formats. This is called inside a catch block. Important: When overriding,
  /// do not call `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual void handleOperationException(
      const std::exception &ex,
      Pistache::Http::ResponseWriter &response) const noexcept;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during processing of the
  /// request in handler functions. May be overridden to return custom error
  /// formats. This is called inside a catch block. Important: When overriding,
  /// do not call `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string>
  handleOperationException(const std::exception &ex) const noexcept;

  /// <summary>
  /// N32-f Context Terminate
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="n32fContextInfo">Custom operation for n32-f context
  /// termination</param>
  virtual void
  post_n32f_terminate(const oai::_3gpp::model::N32fContextInfo &n32fContextInfo,
                      Pistache::Http::ResponseWriter &response) = 0;
};

} // namespace oai::sepp::api

#endif /* N32FContextTerminateApi_H_ */
