/**
 * JOSE Protected Message Forwarding API
 * N32-f Message Forwarding Service.   © 2025, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.4.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "N32FForwardApi.h"
#include "Helpers.h"
#include "sbi_helper.hpp"
#include "sepp_config.hpp"

namespace oai::sepp::api {

using namespace oai::_3gpp::model::helpers;
using namespace oai::_3gpp::model;
using namespace oai::common::sbi;

const std::string N32FForwardApi::base = "/n32f-forward/v1";

N32FForwardApi::N32FForwardApi(
    const std::shared_ptr<Pistache::Rest::Router> &rtr)
    : ApiBase(rtr) {}

void N32FForwardApi::init() { setupRoutes(); }

void N32FForwardApi::setupRoutes() {
  using namespace Pistache::Rest;

  Routes::Options(
      *router, base + "/n32f-process",
      Routes::bind(&N32FForwardApi::n32f_process_options_handler, this));
  Routes::Post(*router, base + "/n32f-process",
               Routes::bind(&N32FForwardApi::post_n32f_process_handler, this));

  // Default handler, called when a route is not found
  router->addCustomHandler(
      Routes::bind(&N32FForwardApi::n32_f_forward_api_default_handler, this));
}

void N32FForwardApi::handleParsingException(
    const std::exception &ex,
    Pistache::Http::ResponseWriter &response) const noexcept {
  std::pair<Pistache::Http::Code, std::string> codeAndError =
      handleParsingException(ex);
  response.send(codeAndError.first, codeAndError.second);
}

std::pair<Pistache::Http::Code, std::string>
N32FForwardApi::handleParsingException(
    const std::exception &ex) const noexcept {
  try {
    throw;
  } catch (nlohmann::detail::exception &e) {
    return std::make_pair(Pistache::Http::Code::Bad_Request, e.what());
    //    } catch (org::openapitools::server::helpers::ValidationException &e) {
    //       return std::make_pair(Pistache::Http::Code::Bad_Request, e.what());
  } catch (std::exception &e) {
    return std::make_pair(Pistache::Http::Code::Internal_Server_Error,
                          e.what());
  }
}

void N32FForwardApi::handleOperationException(
    const std::exception &ex,
    Pistache::Http::ResponseWriter &response) const noexcept {
  std::pair<Pistache::Http::Code, std::string> codeAndError =
      handleOperationException(ex);
  response.send(codeAndError.first, codeAndError.second);
}

std::pair<Pistache::Http::Code, std::string>
N32FForwardApi::handleOperationException(
    const std::exception &ex) const noexcept {
  return std::make_pair(Pistache::Http::Code::Internal_Server_Error, ex.what());
}

void N32FForwardApi::n32f_process_options_handler(
    const Pistache::Rest::Request &request,
    Pistache::Http::ResponseWriter response) {
  try {

    try {

      this->n32f_process_options(response);
    } catch (Pistache::Http::HttpError &e) {
      response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
      return;
    } catch (std::exception &e) {
      this->handleOperationException(e, response);
      return;
    }

  } catch (std::exception &e) {
    response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}

void N32FForwardApi::post_n32f_process_handler(
    const Pistache::Rest::Request &request,
    Pistache::Http::ResponseWriter response) {
  try {

    // Getting the body param

    N32fReformattedReqMsg n32fReformattedReqMsg;

    // Getting the header params
    auto contentEncoding = request.headers().tryGetRaw("Content-Encoding");
    auto acceptEncoding = request.headers().tryGetRaw("Accept-Encoding");
    auto r_3gpp_Sbi_Message_Priority =
        request.headers().tryGetRaw("3gpp-Sbi-Message-Priority");

    try {
      nlohmann::json::parse(request.body()).get_to(n32fReformattedReqMsg);
      n32fReformattedReqMsg.validate();
    } catch (std::exception &e) {
      this->handleParsingException(e, response);
      return;
    }

    // try {

    //     this->post_n32f_process(n32fReformattedReqMsg, contentEncoding,
    //     acceptEncoding, r_3gpp_Sbi_Message_Priority, response); } catch
    //     (Pistache::Http::HttpError &e) {
    //         response.send(static_cast<Pistache::Http::Code>(e.code()),
    //         e.what()); return;
    //     } catch (std::exception &e) {
    //         this->handleOperationException(e, response);
    //         return;
    //     }

  } catch (std::exception &e) {
    response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}

void N32FForwardApi::n32_f_forward_api_default_handler(
    const Pistache::Rest::Request &, Pistache::Http::ResponseWriter response) {
  response.send(Pistache::Http::Code::Not_Found,
                "The requested method does not exist");
}

} // namespace oai::sepp::api
