/**
 * JOSE Protected Message Forwarding API
 * N32-f Message Forwarding Service.   © 2025, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.4.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * N32FForwardApi.h
 *
 *
 */

#ifndef N32FForwardApi_H_
#define N32FForwardApi_H_

#include "ApiBase.h"

#include <pistache/http.h>
#include <pistache/http_headers.h>
#include <pistache/router.h>

#include <optional>
#include <utility>

#include "N32fReformattedReqMsg.h"
#include "N32fReformattedRspMsg.h"
#include "ProblemDetails.h"
#include "ProblemDetailsMsgForwarding.h"
#include <string>

namespace oai::sepp::api {

class N32FForwardApi : public ApiBase {
public:
  explicit N32FForwardApi(const std::shared_ptr<Pistache::Rest::Router> &rtr);
  ~N32FForwardApi() override = default;
  void init() override;

  static const std::string base;

private:
  void setupRoutes();

  void n32f_process_options_handler(const Pistache::Rest::Request &request,
                                    Pistache::Http::ResponseWriter response);
  void post_n32f_process_handler(const Pistache::Rest::Request &request,
                                 Pistache::Http::ResponseWriter response);
  void
  n32_f_forward_api_default_handler(const Pistache::Rest::Request &request,
                                    Pistache::Http::ResponseWriter response);

  /// <summary>
  /// Helper function to handle unexpected Exceptions during Parameter parsing
  /// and validation. May be overridden to return custom error formats. This is
  /// called inside a catch block. Important: When overriding, do not call
  /// `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual void handleParsingException(
      const std::exception &ex,
      Pistache::Http::ResponseWriter &response) const noexcept;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during Parameter parsing
  /// and validation. May be overridden to return custom error formats. This is
  /// called inside a catch block. Important: When overriding, do not call
  /// `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string>
  handleParsingException(const std::exception &ex) const noexcept;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during processing of the
  /// request in handler functions. May be overridden to return custom error
  /// formats. This is called inside a catch block. Important: When overriding,
  /// do not call `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual void handleOperationException(
      const std::exception &ex,
      Pistache::Http::ResponseWriter &response) const noexcept;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during processing of the
  /// request in handler functions. May be overridden to return custom error
  /// formats. This is called inside a catch block. Important: When overriding,
  /// do not call `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string>
  handleOperationException(const std::exception &ex) const noexcept;

  /// <summary>
  /// Discover communication options supported by next hop (RI or SEPP)
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  virtual void
  n32f_process_options(Pistache::Http::ResponseWriter &response) = 0;
  /// <summary>
  /// N32-f Message Forwarding
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="n32fReformattedReqMsg">Custom operation N32-f Message
  /// Forwarding</param> <param name="contentEncoding">Content-Encoding,
  /// described in IETF RFC 9110 (optional, default to &quot;&quot;)</param>
  /// <param name="acceptEncoding">Accept-Encoding, described in IETF RFC 9110
  /// (optional, default to &quot;&quot;)</param> <param
  /// name="r_3gpp_Sbi_Message_Priority">3gpp-Sbi-Message-Priority, defined in
  /// 3GPP TS 29.500 (optional, default to &quot;&quot;)</param>
  virtual void post_n32f_process(
      const oai::_3gpp::model::N32fReformattedReqMsg &n32fReformattedReqMsg,
      const std::optional<Pistache::Http::Header::Raw> &contentEncoding,
      const std::optional<Pistache::Http::Header::Raw> &acceptEncoding,
      const std::optional<Pistache::Http::Header::Raw>
          &r_3gpp_Sbi_Message_Priority,
      Pistache::Http::ResponseWriter &response) = 0;
};

} // namespace oai::sepp::api

#endif /* N32FForwardApi_H_ */
