/**
 * N32 Handshake API
 * N32-c Handshake Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.4.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * ParameterExchangeApi.h
 *
 *
 */

#ifndef ParameterExchangeApi_H_
#define ParameterExchangeApi_H_

#include "ApiBase.h"

#include <pistache/http.h>
#include <pistache/http_headers.h>
#include <pistache/router.h>

#include <optional>
#include <utility>

#include "ProblemDetails.h"
#include "SecParamExchReqData.h"
#include "SecParamExchRspData.h"

namespace oai::sepp::api {

class ParameterExchangeApi : public ApiBase {
public:
  explicit ParameterExchangeApi(
      const std::shared_ptr<Pistache::Rest::Router> &rtr);
  ~ParameterExchangeApi() override = default;
  void init() override;

  static const std::string base;

private:
  void setupRoutes();

  void post_exchange_params_handler(const Pistache::Rest::Request &request,
                                    Pistache::Http::ResponseWriter response);
  void parameter_exchange_api_default_handler(
      const Pistache::Rest::Request &request,
      Pistache::Http::ResponseWriter response);

  /// <summary>
  /// Helper function to handle unexpected Exceptions during Parameter parsing
  /// and validation. May be overridden to return custom error formats. This is
  /// called inside a catch block. Important: When overriding, do not call
  /// `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual void handleParsingException(
      const std::exception &ex,
      Pistache::Http::ResponseWriter &response) const noexcept;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during Parameter parsing
  /// and validation. May be overridden to return custom error formats. This is
  /// called inside a catch block. Important: When overriding, do not call
  /// `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string>
  handleParsingException(const std::exception &ex) const noexcept;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during processing of the
  /// request in handler functions. May be overridden to return custom error
  /// formats. This is called inside a catch block. Important: When overriding,
  /// do not call `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual void handleOperationException(
      const std::exception &ex,
      Pistache::Http::ResponseWriter &response) const noexcept;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during processing of the
  /// request in handler functions. May be overridden to return custom error
  /// formats. This is called inside a catch block. Important: When overriding,
  /// do not call `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string>
  handleOperationException(const std::exception &ex) const noexcept;

  /// <summary>
  /// Parameter Exchange
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="secParamExchReqData">Custom operation for parameter
  /// exchange</param>
  virtual void post_exchange_params(
      const oai::_3gpp::model::SecParamExchReqData &secParamExchReqData,
      Pistache::Http::ResponseWriter &response) = 0;
};

} // namespace oai::sepp::api

#endif /* ParameterExchangeApi_H_ */
