/**
 * SEPP Telescopic FQDN Mapping API
 * SEPP Telescopic FQDN Mapping Service.   © 2026, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.3.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * TelescopicMappingDocumentApi.h
 *
 *
 */

#ifndef TelescopicMappingDocumentApi_H_
#define TelescopicMappingDocumentApi_H_

#include "ApiBase.h"

#include <pistache/http.h>
#include <pistache/http_headers.h>
#include <pistache/router.h>

#include <optional>
#include <utility>

#include "ProblemDetails.h"
#include "TelescopicMapping.h"
#include <string>

namespace oai::sepp::api {

class TelescopicMappingDocumentApi : public ApiBase {
public:
  explicit TelescopicMappingDocumentApi(
      const std::shared_ptr<Pistache::Rest::Router> &rtr);
  ~TelescopicMappingDocumentApi() override = default;
  void init() override;

  static const std::string base;

private:
  void setupRoutes();

  void get_telescopic_mapping_handler(const Pistache::Rest::Request &request,
                                      Pistache::Http::ResponseWriter response);
  void telescopic_mapping_document_api_default_handler(
      const Pistache::Rest::Request &request,
      Pistache::Http::ResponseWriter response);

  /// <summary>
  /// Helper function to handle unexpected Exceptions during Parameter parsing
  /// and validation. May be overridden to return custom error formats. This is
  /// called inside a catch block. Important: When overriding, do not call
  /// `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual void handleParsingException(
      const std::exception &ex,
      Pistache::Http::ResponseWriter &response) const noexcept;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during Parameter parsing
  /// and validation. May be overridden to return custom error formats. This is
  /// called inside a catch block. Important: When overriding, do not call
  /// `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string>
  handleParsingException(const std::exception &ex) const noexcept;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during processing of the
  /// request in handler functions. May be overridden to return custom error
  /// formats. This is called inside a catch block. Important: When overriding,
  /// do not call `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual void handleOperationException(
      const std::exception &ex,
      Pistache::Http::ResponseWriter &response) const noexcept;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during processing of the
  /// request in handler functions. May be overridden to return custom error
  /// formats. This is called inside a catch block. Important: When overriding,
  /// do not call `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string>
  handleOperationException(const std::exception &ex) const noexcept;

  /// <summary>
  /// Maps an FQDN to/from a telescopic FQDN
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="foreignFqdn">FQDN of the NF in the foreign PLMN (optional,
  /// default to &quot;&quot;)</param> <param name="telescopicLabel">Telescopic
  /// Label (optional, default to &quot;&quot;)</param>
  virtual void
  get_telescopic_mapping(const std::optional<std::string> &foreignFqdn,
                         const std::optional<std::string> &telescopicLabel,
                         Pistache::Http::ResponseWriter &response) = 0;
};

} // namespace oai::sepp::api

#endif /* TelescopicMappingDocumentApi_H_ */
