/**
 * SEPP Telescopic FQDN Mapping API
 * SEPP Telescopic FQDN Mapping Service.   © 2026, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.3.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "TelescopicMappingDocumentApi.h"
#include "Helpers.h"
#include "sbi_helper.hpp"
#include "sepp_config.hpp"

namespace oai::sepp::api {

using namespace oai::_3gpp::model::helpers;
using namespace oai::_3gpp::model;
using namespace oai::common::sbi;

const std::string TelescopicMappingDocumentApi::base = "/nsepp-telescopic/v1";

TelescopicMappingDocumentApi::TelescopicMappingDocumentApi(
    const std::shared_ptr<Pistache::Rest::Router> &rtr)
    : ApiBase(rtr) {}

void TelescopicMappingDocumentApi::init() { setupRoutes(); }

void TelescopicMappingDocumentApi::setupRoutes() {
  using namespace Pistache::Rest;

  Routes::Get(
      *router, base + "/mapping",
      Routes::bind(
          &TelescopicMappingDocumentApi::get_telescopic_mapping_handler, this));

  // Default handler, called when a route is not found
  router->addCustomHandler(
      Routes::bind(&TelescopicMappingDocumentApi::
                       telescopic_mapping_document_api_default_handler,
                   this));
}

void TelescopicMappingDocumentApi::handleParsingException(
    const std::exception &ex,
    Pistache::Http::ResponseWriter &response) const noexcept {
  std::pair<Pistache::Http::Code, std::string> codeAndError =
      handleParsingException(ex);
  response.send(codeAndError.first, codeAndError.second);
}

std::pair<Pistache::Http::Code, std::string>
TelescopicMappingDocumentApi::handleParsingException(
    const std::exception &ex) const noexcept {
  try {
    throw;
  } catch (nlohmann::detail::exception &e) {
    return std::make_pair(Pistache::Http::Code::Bad_Request, e.what());
    //    } catch (org::openapitools::server::helpers::ValidationException &e) {
    //       return std::make_pair(Pistache::Http::Code::Bad_Request, e.what());
  } catch (std::exception &e) {
    return std::make_pair(Pistache::Http::Code::Internal_Server_Error,
                          e.what());
  }
}

void TelescopicMappingDocumentApi::handleOperationException(
    const std::exception &ex,
    Pistache::Http::ResponseWriter &response) const noexcept {
  std::pair<Pistache::Http::Code, std::string> codeAndError =
      handleOperationException(ex);
  response.send(codeAndError.first, codeAndError.second);
}

std::pair<Pistache::Http::Code, std::string>
TelescopicMappingDocumentApi::handleOperationException(
    const std::exception &ex) const noexcept {
  return std::make_pair(Pistache::Http::Code::Internal_Server_Error, ex.what());
}

void TelescopicMappingDocumentApi::get_telescopic_mapping_handler(
    const Pistache::Rest::Request &request,
    Pistache::Http::ResponseWriter response) {
  try {

    // Getting the query params
    auto foreignFqdnQuery = request.query().get("foreign-fqdn");
    std::optional<std::string> foreignFqdn;
    // if (foreignFqdnQuery.has_value()) {
    //     std::string valueQuery_instance;
    //     if (fromStringValue(foreignFqdnQuery.value(), valueQuery_instance)) {
    //         foreignFqdn = valueQuery_instance;
    //     }
    // }
    // auto telescopicLabelQuery = request.query().get("telescopic-label");
    // std::optional<std::string> telescopicLabel;
    // if (telescopicLabelQuery.has_value()) {
    //     std::string valueQuery_instance;
    //     if (fromStringValue(telescopicLabelQuery.value(),
    //     valueQuery_instance)) {
    //         telescopicLabel = valueQuery_instance;
    //     }
    // }

    // try {

    //     this->get_telescopic_mapping(foreignFqdn, telescopicLabel, response);
    //     } catch (Pistache::Http::HttpError &e) {
    //         response.send(static_cast<Pistache::Http::Code>(e.code()),
    //         e.what()); return;
    //     } catch (std::exception &e) {
    //         this->handleOperationException(e, response);
    //         return;
    //     }

  } catch (std::exception &e) {
    response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}

void TelescopicMappingDocumentApi::
    telescopic_mapping_document_api_default_handler(
        const Pistache::Rest::Request &,
        Pistache::Http::ResponseWriter response) {
  response.send(Pistache::Http::Code::Not_Found,
                "The requested method does not exist");
}

} // namespace oai::sepp::api
