/**
 * RNI API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI
 *
 * OpenAPI spec version: 1.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#ifndef FILE_SEPP_API_SERVER_SEEN
#define FILE_SEPP_API_SERVER_SEEN

#include "pistache/endpoint.h"
#include "pistache/http.h"
#include "pistache/router.h"
#ifdef __linux__
#include <signal.h>
#include <unistd.h>
#include <vector>
#endif

// #include "SubscriptionsCollectionApiImpl.h"
#include "TelescopicMappingDocumentApi.h"
// #include "SecurityCapabilityNegotiationApi.h"
// #include "ParameterExchangeApi.h"
// #include "N32FForwardApi.h"
// #include "N32FErrorReportApi.h"
// #include "N32FContextTerminateApi.h"

#include "logger.hpp"
#include "sepp_app.hpp"

using namespace oai::sepp::api;
using namespace oai::_3gpp::model;

class SEPPApiServer {
public:
  SEPPApiServer(const Pistache::Address address,
                const std::unique_ptr<oai::sepp::app::sepp_app> &sepp_app_inst)
      : m_httpEndpoint(std::make_shared<Pistache::Http::Endpoint>(address)) {
    m_router = std::make_shared<Pistache::Rest::Router>();
    m_address = address.host() + ":" + (address.port()).toString();

    // m_subscriptionsCollectionApiImpl =
    //     std::make_shared<SubscriptionsCollectionApiImpl>(
    //         m_router, sepp_app_inst, m_address);

    // m_accessTokenRequestApiImpl =
    // std::make_shared<AccessTokenRequestApiImpl>(
    //     m_router, sepp_app_inst, m_address);
  }
  void init(size_t thr = 1);
  void start();
  void shutdown();

private:
  std::shared_ptr<Pistache::Http::Endpoint> m_httpEndpoint;
  std::shared_ptr<Pistache::Rest::Router> m_router;

  //   std::shared_ptr<SubscriptionsCollectionApiImpl>
  //       m_subscriptionsCollectionApiImpl;

  std::string m_address;
};

#endif
