#/*
# * SPDX-License-Identifier: LicenseRef-CSSL-1.0
# */

#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface SEPP service
#   Valid for Ubuntu-24.04 (noble)
#
#---------------------------------------------------------------------

#---------------------------------------------------------------------
# BASE IMAGE
#---------------------------------------------------------------------
ARG BASE_IMAGE=ubuntu:noble
FROM $BASE_IMAGE AS oai-sepp-base

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris
ENV IS_DOCKERFILE=1
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade --yes && \
    DEBIAN_FRONTEND=noninteractive apt-get install --yes \
      psmisc \
      git \
  && rm -rf /var/lib/apt/lists/*

# Some GIT configuration command quite useful
RUN git config --global https.postBuffer 123289600 && \
    git config --global http.sslverify false

# Copying source code
WORKDIR /openair-sepp
COPY ./build/scripts /openair-sepp/build/scripts/
COPY ./build/common-build /openair-sepp/build/common-build
COPY ./build/sepp/CMakeLists.txt /openair-sepp/build/sepp/CMakeLists.txt

# Installing all the needed libraries/packages to build and run SEPP
WORKDIR /openair-sepp/build/scripts
RUN ./build_sepp --install-deps --force && \
    ldconfig


#---------------------------------------------------------------------
# BUILDER IMAGE
#---------------------------------------------------------------------
FROM oai-sepp-base AS oai-sepp-builder
# Copying source code
COPY . /openair-sepp
# Building SEPP
WORKDIR /openair-sepp/build/scripts
RUN ./build_sepp --clean --Verbose --build-type Release --jobs && \
    ldd /openair-sepp/build/sepp/build/sepp && \
    mv /openair-sepp/build/sepp/build/sepp /openair-sepp/build/sepp/build/oai-sepp

#---------------------------------------------------------------------
# TARGET IMAGE
#---------------------------------------------------------------------
FROM $BASE_IMAGE AS oai-sepp
ARG TARGETPLATFORM
ARG VERSION=v4.47.1
ENV TARGETPLATFORM=${TARGETPLATFORM}

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris
# We install some debug tools for the moment in addition of mandatory libraries
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade --yes && \
    DEBIAN_FRONTEND=noninteractive apt-get install --yes \
# Debug Tools that are not mandatory
      tzdata \
      psmisc \
      net-tools \
      tcpdump \
      iputils-ping \
      bc \
      wget \
# Mandatory packages for the NF to run
      openssl \
      libboost-thread1.83.0 \
      libcurl4-gnutls-dev \
      librtmp1 \
      libpsl5t64 \
      libyaml-cpp0.8 \
  && rm -rf /var/lib/apt/lists/*

# Copying executable and generated libraries
WORKDIR /openair-sepp/bin
COPY --from=oai-sepp-builder \
    /openair-sepp/build/sepp/build/oai-sepp \
    /openair-sepp/scripts/healthcheck.sh \
    ./

RUN echo "Target platform is: ${TARGETPLATFORM}" && \
    case "${TARGETPLATFORM}" in \
      "linux/amd64") BINARY="yq_linux_amd64"; ;; \
      "linux/arm64") BINARY="yq_linux_arm64"; ;; \
      *) echo "Unsupported platform"; exit 1; ;; \
    esac && \
    wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY} -O /usr/bin/yq && \
    chmod +x /usr/bin/yq

WORKDIR /usr/local/lib/
COPY --from=oai-sepp-builder \
# Copying only the packages built from source
    /usr/local/lib/libpistache.so* \
    /usr/local/lib/libnghttp2.so.14 \
    /usr/local/lib/libnghttp2_asio.so.1 \
    /usr/local/lib/libyaml-cpp.so.0.? \
    /usr/local/lib/libcpr.so.1* \
    /usr/local/lib/libfmt.so \
    ./

RUN ldconfig && \
    ldd /openair-sepp/bin/oai-sepp

# Copying template configuration files
# The configuration folder will be flat
WORKDIR /openair-sepp/etc
COPY --from=oai-sepp-builder \
    /openair-sepp/etc/config.yaml \
    /openair-sepp/scripts/entrypoint.sh \
    ./

WORKDIR /openair-sepp

ARG GIT_COMMIT

LABEL org.opencontainers.image.authors="OpenAirInterface <oaicicdteam@openairinterface.org>" \
      org.opencontainers.image.vendor="OpenAirInterface Software Alliance" \
      org.opencontainers.image.licenses="Collaborative Standards Software License v1.0" \
      org.opencontainers.image.title="OAI SEPP" \
      org.opencontainers.image.description="OpenAirInterface Network Slicing Selection Function" \
      org.opencontainers.image.revision="commit:${GIT_COMMIT}"


EXPOSE 80/tcp 8080/tcp
# healthcheck
HEALTHCHECK --interval=10s \
            --timeout=15s \
            --retries=6 \
    CMD /openair-sepp/bin/healthcheck.sh
ENTRYPOINT ["/openair-sepp/etc/entrypoint.sh"]

CMD ["/openair-sepp/bin/oai-sepp", "-c", "/openair-sepp/etc/config.yaml", "-o"]
