#/*
# * SPDX-License-Identifier: LicenseRef-CSSL-1.0
# */

#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface SEPP service
#  Valid for Rocky Linux 9.+ 
#
#---------------------------------------------------------------------

#---------------------------------------------------------------------
# BUILDER IMAGE
#---------------------------------------------------------------------
FROM docker.io/rockylinux:9 AS oai-sepp-builder

ENV IS_DOCKERFILE=1

RUN dnf install 'dnf-command(config-manager)' -y && \
    dnf install epel-release -y && crb enable && \
    dnf update -y && \
    # here just to display the current version
    cat /etc/os-release && \
    dnf install -y \
        psmisc \
        git \
        diffutils \
        libasan \
        wget \
        file && \
    echo "/usr/local/lib" > /etc/ld.so.conf.d/local-lib.conf && \
    echo "/usr/local/lib64" >> /etc/ld.so.conf.d/local-lib.conf

# Some GIT configuration command quite useful
RUN git config --global https.postBuffer 123289600 && \
    git config --global http.sslverify false

# Copying source code
WORKDIR /openair-sepp
COPY . /openair-sepp

# Installing and Building SEPP
WORKDIR /openair-sepp/build/scripts
RUN ./build_sepp --install-deps --force && \
    ldconfig
RUN ./build_sepp --clean --Verbose --build-type Release --jobs && \
    ldd /openair-sepp/build/sepp/build/sepp && \
    mv /openair-sepp/build/sepp/build/sepp /openair-sepp/build/sepp/build/oai-sepp

FROM mikefarah/yq:latest as yq-source

#---------------------------------------------------------------------
# TARGET IMAGE
#---------------------------------------------------------------------
FROM docker.io/rockylinux:9-minimal as oai-sepp
ENV TZ=Europe/Paris

# We install some debug tools for the moment in addition of mandatory libraries
RUN microdnf update -y && \
    microdnf install -y \
# Debug Tools that are not mandatory
      tzdata \
      procps-ng \
      psmisc \
      net-tools \
      iputils \
      tcpdump \
# Mandatory packages for the NF to run
#      libasan \
      libicu \
      boost \
      libevent \
      findutils && \
    microdnf clean all -y && \
    rm -rf /var/cache/yum /var/cache/dnf

# Copying executable and generated libraries
WORKDIR /openair-sepp/bin
COPY --from=oai-sepp-builder \
    /openair-sepp/build/sepp/build/oai-sepp \
    /openair-sepp/scripts/healthcheck.sh \
    ./
COPY --from=yq-source /usr/bin/yq /usr/bin

COPY --from=oai-sepp-builder \
# Copying only the packages built from source
    /usr/local/lib64/libpistache.so.0 \
    /usr/local/lib/libnghttp2_asio.so \
    /usr/local/lib/libnghttp2_asio.so.1 \
    /usr/local/lib64/libspdlog.so \
    /usr/local/lib64/libfmt.so \
# libyaml-cpp is installed via epel-8
# and epel-8 cannot be installed on ubi-minimal
    /usr/local/lib64/libyaml-cpp.so.0.* \
    /usr/local/lib64/libcpr.so.1 \
    /usr/lib64/

RUN ldconfig && \
    ldd /openair-sepp/bin/oai-sepp

# Copying template configuration files
# The configuration folder will be flat
WORKDIR /openair-sepp/etc
COPY --from=oai-sepp-builder \
    /openair-sepp/etc/config.yaml \
    ./

WORKDIR /openair-sepp

# expose ports
EXPOSE 80/tcp 8080/tcp
# healthcheck
HEALTHCHECK --interval=10s \
            --timeout=15s \
            --retries=6 \
    CMD /openair-sepp/bin/healthcheck.sh

CMD ["/openair-sepp/bin/oai-sepp", "-c", "/openair-sepp/etc/config.yaml", "-o"]
