/**
 * JOSE Protected Message Forwarding API
 * N32-f Message Forwarding Service.   © 2025, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.4.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "N32FForwardApiImpl.h"
#include "3gpp_29.500.h"
#include "Helpers.h"
#include "ProblemDetails.h"
#include "logger.hpp"
#include "sepp_app.hpp"
#include "sepp_config.hpp"
#include <string>

namespace oai::sepp::api {

using namespace oai::_3gpp::model::helpers;
using namespace oai::_3gpp::model;
using namespace sepp;

N32FForwardApiImpl::N32FForwardApiImpl(
    const std::shared_ptr<Pistache::Rest::Router> &rtr)
    : N32FForwardApi(rtr) {}

void N32FForwardApiImpl::n32f_process_options(
    Pistache::Http::ResponseWriter &response) {
  response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}
void N32FForwardApiImpl::post_n32f_process(
    const N32fReformattedReqMsg &n32fReformattedReqMsg,
    const std::optional<Pistache::Http::Header::Raw> &contentEncoding,
    const std::optional<Pistache::Http::Header::Raw> &acceptEncoding,
    const std::optional<Pistache::Http::Header::Raw>
        &r_3gpp_Sbi_Message_Priority,
    Pistache::Http::ResponseWriter &response) {
  response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

} // namespace oai::sepp::api
