/**
 * N32 Handshake API
 * N32-c Handshake Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.4.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * N32FContextTerminateApiImpl.h
 *
 *
 */

#ifndef N32_F_CONTEXT_TERMINATE_API_IMPL_H_
#define N32_F_CONTEXT_TERMINATE_API_IMPL_H_

#include <memory>
#include <optional>
#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>

#include <N32FContextTerminateApi.h>

#include "N32fContextInfo.h"
#include "ProblemDetails.h"

namespace oai::sepp::api {

using namespace oai::_3gpp::model;
// using namespace oai::common::sbi;

class N32FContextTerminateApiImpl
    : public oai::sepp::api::N32FContextTerminateApi {
public:
  explicit N32FContextTerminateApiImpl(
      const std::shared_ptr<Pistache::Rest::Router> &rtr);
  ~N32FContextTerminateApiImpl() override = default;

  void post_n32f_terminate(const N32fContextInfo &n32fContextInfo,
                           Pistache::Http::ResponseWriter &response);
};

} // namespace oai::sepp::api

#endif
