/**
 * JOSE Protected Message Forwarding API
 * N32-f Message Forwarding Service.   © 2025, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.4.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * N32FForwardApiImpl.h
 *
 *
 */

#ifndef N32_F_FORWARD_API_IMPL_H_
#define N32_F_FORWARD_API_IMPL_H_

#include <memory>
#include <optional>
#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>

#include <N32FForwardApi.h>

#include "N32fReformattedReqMsg.h"
#include "N32fReformattedRspMsg.h"
#include "ProblemDetails.h"
#include "ProblemDetailsMsgForwarding.h"
#include <string>

namespace oai::sepp::api {

using namespace oai::_3gpp::model;
// using namespace oai::common::sbi;

class N32FForwardApiImpl : public oai::sepp::api::N32FForwardApi {
public:
  explicit N32FForwardApiImpl(
      const std::shared_ptr<Pistache::Rest::Router> &rtr);
  ~N32FForwardApiImpl() override = default;

  void n32f_process_options(Pistache::Http::ResponseWriter &response);
  void post_n32f_process(
      const N32fReformattedReqMsg &n32fReformattedReqMsg,
      const std::optional<Pistache::Http::Header::Raw> &contentEncoding,
      const std::optional<Pistache::Http::Header::Raw> &acceptEncoding,
      const std::optional<Pistache::Http::Header::Raw>
          &r_3gpp_Sbi_Message_Priority,
      Pistache::Http::ResponseWriter &response);
};

} // namespace oai::sepp::api

#endif
