/**
 * N32 Handshake API
 * N32-c Handshake Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.4.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * ParameterExchangeApiImpl.h
 *
 *
 */

#ifndef PARAMETER_EXCHANGE_API_IMPL_H_
#define PARAMETER_EXCHANGE_API_IMPL_H_

#include <memory>
#include <optional>
#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>

#include <ParameterExchangeApi.h>

#include "ProblemDetails.h"
#include "SecParamExchReqData.h"
#include "SecParamExchRspData.h"

namespace oai::sepp::api {

using namespace oai::_3gpp::model;
// using namespace oai::common::sbi;

class ParameterExchangeApiImpl : public oai::sepp::api::ParameterExchangeApi {
public:
  explicit ParameterExchangeApiImpl(
      const std::shared_ptr<Pistache::Rest::Router> &rtr);
  ~ParameterExchangeApiImpl() override = default;

  void post_exchange_params(const SecParamExchReqData &secParamExchReqData,
                            Pistache::Http::ResponseWriter &response);
};

} // namespace oai::sepp::api

#endif
