/**
 * N32 Handshake API
 * N32-c Handshake Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.4.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * SecurityCapabilityNegotiationApiImpl.h
 *
 *
 */

#ifndef SECURITY_CAPABILITY_NEGOTIATION_API_IMPL_H_
#define SECURITY_CAPABILITY_NEGOTIATION_API_IMPL_H_

#include <memory>
#include <optional>
#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>

#include <SecurityCapabilityNegotiationApi.h>

#include "ExtRedirectResponse.h"
#include "ProblemDetails.h"
#include "SecNegotiateReqData.h"
#include "SecNegotiateRspData.h"

namespace oai::sepp::api {

using namespace oai::_3gpp::model;
// using namespace oai::common::sbi;

class SecurityCapabilityNegotiationApiImpl
    : public oai::sepp::api::SecurityCapabilityNegotiationApi {
public:
  explicit SecurityCapabilityNegotiationApiImpl(
      const std::shared_ptr<Pistache::Rest::Router> &rtr);
  ~SecurityCapabilityNegotiationApiImpl() override = default;

  void post_exchange_capability(const SecNegotiateReqData &secNegotiateReqData,
                                Pistache::Http::ResponseWriter &response);
};

} // namespace oai::sepp::api

#endif
