/**
 * N32 Handshake API
 * N32-c Handshake Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.4.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "SecurityCapabilityNegotiationApiImpl.h"
#include "3gpp_29.500.h"
#include "Helpers.h"
#include "ProblemDetails.h"
#include "logger.hpp"
#include "sepp_app.hpp"
#include "sepp_config.hpp"
#include <string>

namespace oai::sepp::api {

using namespace oai::_3gpp::model::helpers;
using namespace oai::_3gpp::model;
using namespace sepp;

SecurityCapabilityNegotiationApiImpl::SecurityCapabilityNegotiationApiImpl(
    const std::shared_ptr<Pistache::Rest::Router> &rtr)
    : SecurityCapabilityNegotiationApi(rtr) {}

void SecurityCapabilityNegotiationApiImpl::post_exchange_capability(
    const SecNegotiateReqData &secNegotiateReqData,
    Pistache::Http::ResponseWriter &response) {
  response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

} // namespace oai::sepp::api
