/**
 * SEPP Telescopic FQDN Mapping API
 * SEPP Telescopic FQDN Mapping Service.   © 2026, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.3.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * TelescopicMappingDocumentApiImpl.h
 *
 *
 */

#ifndef TELESCOPIC_MAPPING_DOCUMENT_API_IMPL_H_
#define TELESCOPIC_MAPPING_DOCUMENT_API_IMPL_H_

#include <memory>
#include <optional>
#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>

#include <TelescopicMappingDocumentApi.h>

#include "ProblemDetails.h"
#include "TelescopicMapping.h"
#include <string>

namespace oai::sepp::api {

using namespace oai::_3gpp::model;
// using namespace oai::common::sbi;

class TelescopicMappingDocumentApiImpl
    : public oai::sepp::api::TelescopicMappingDocumentApi {
public:
  explicit TelescopicMappingDocumentApiImpl(
      const std::shared_ptr<Pistache::Rest::Router> &rtr);
  ~TelescopicMappingDocumentApiImpl() override = default;

  void get_telescopic_mapping(const std::optional<std::string> &foreignFqdn,
                              const std::optional<std::string> &telescopicLabel,
                              Pistache::Http::ResponseWriter &response);
};

} // namespace oai::sepp::api

#endif
